services:
  redis:
    image: redis:7-alpine
    container_name: recipe-explorer-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    container_name: recipe-explorer-app
    volumes:
      - ./:/app:cached
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
